interface:
  image: python:onbuild
  restart: always
  links:
    - redis
    - mongo
  volumes:
    - ./lib:/usr/src/app
  ports:
    - 8000:8000
  entrypoint: ["python", "-m", "app"] 

jupyter:
  image: jupyter/all-spark
  restart: always
  links:
    - redis
    - mongo
  volumes:
    - .:/home/jovyan/work
  ports:
    - 8001:8888

mongo:
  image: mongo
  volumes_from:
    - mongodata

mongodata:
  image: mongo
  command: echo 'Data Container for MongoDB'
  volumes:
    - data/mongo

redis:
  image: redis
  ports:
    - 6379:6379
  volumes_from:
    - redisdata

redisdata:
  image: redis
  command: echo 'Data Container for Redis'
  volumes:
    - data/redis

rq:
  image: python:onbuild
  links:
    - redis
    - mongo
  restart: always
  entrypoint: ["rq", "worker", "-c", "conf.rq_settings"]

