jupyter:
  build: docker/jupyter
  restart: always
  links:
    - redis
    - postgres
  volumes:
    - .:/home/jovyan/work
  ports:
    - 8001:8888

postgres:
  build: docker/postgres
  volumes:
    - .:/home
  volumes_from:
    - postgresdata

postgresdata:
  image: postgres
  command: echo 'Data Container for PostgresDB'
  volumes:
<<<<<<< Updated upstream
    - /data/mongo
=======
    - /var/lib/postgresql
    - /data/postgres
>>>>>>> Stashed changes

redis:
  image: redis
  volumes_from:
    - redisdata

redisdata:
  image: redis
  command: echo 'Data Container for Redis'
  volumes:
    - /data/redis

rq:
  build: docker/python
  links:
    - redis
    - postgres
  restart: always
  entrypoint: ["rq", "worker", "-c", "lib.conf.rq_settings"]
  volumes:
    - .:/usr/src/app

webserver:
  build: docker/python
  restart: always
  links:
    - redis
    - postgres
  volumes:
    - .:/usr/src/app
  ports:
    - 8000:8000
  entrypoint: ["python", "-m", "main"] 

