interface:
  build: lib
  restart: always
  links:
    - redis
    - mongo
  volumes:
    - ./lib:/usr/src/app
  ports:
    - 8000:8000

rq:
  build: lib
  links:
    - redis
    - mongo
  restart: always
  entrypoint: ["rq", "worker", "-c", "conf.rq_settings"]

mongo:
  image: mongo
  volumes_from:
    - mongodata

mongodata:
  image: mongo
  command: echo 'Data Container for MongoDB'
  volumes:
    - data/mongo

redis:
  image: redis
  ports:
    - 6379:6379
  volumes_from:
    - redisdata

redisdata:
  image: redis
  command: echo 'Data Container for Redis'
  volumes:
    - data/redis
